name: plants_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  floor: ^1.2.0
  provider: ^6.0.2
  flutter_bloc: 8.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  floor_generator: ^1.2.0
  build_runner: ^2.1.2


flutter:

  uses-material-design: true

